/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface FinderMessage {
  'id' : bigint,
  'sentAt' : Timestamp,
  'messageText' : string,
  'finderPhone' : [] | [string],
  'keyId' : KeyId,
}
export type KeyId = string;
export type KeyType = { 'Car' : null } |
  { 'Bike' : null } |
  { 'Home' : null } |
  { 'Office' : null };
export interface OwnerKeyInfo {
  'id' : KeyId,
  'lostMode' : boolean,
  'name' : string,
  'createdAt' : Timestamp,
  'keyType' : KeyType,
}
export interface PublicKeyInfo {
  'id' : KeyId,
  'lostMode' : boolean,
  'name' : string,
  'keyType' : KeyType,
}
export type Timestamp = bigint;
export interface _SERVICE {
  'addKey' : ActorMethod<[string, KeyType], string>,
  'getKeyInfo' : ActorMethod<[string], [] | [PublicKeyInfo]>,
  'getMessages' : ActorMethod<[string], Array<FinderMessage>>,
  'getMyKeys' : ActorMethod<[], Array<OwnerKeyInfo>>,
  'registerOwner' : ActorMethod<[string, string], undefined>,
  'sendFinderMessage' : ActorMethod<[string, string, [] | [string]], undefined>,
  'setLostMode' : ActorMethod<[string, boolean], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];