/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const KeyType = IDL.Variant({
  'Car' : IDL.Null,
  'Bike' : IDL.Null,
  'Home' : IDL.Null,
  'Office' : IDL.Null,
});
export const KeyId = IDL.Text;
export const PublicKeyInfo = IDL.Record({
  'id' : KeyId,
  'lostMode' : IDL.Bool,
  'name' : IDL.Text,
  'keyType' : KeyType,
});
export const Timestamp = IDL.Int;
export const FinderMessage = IDL.Record({
  'id' : IDL.Nat,
  'sentAt' : Timestamp,
  'messageText' : IDL.Text,
  'finderPhone' : IDL.Opt(IDL.Text),
  'keyId' : KeyId,
});
export const OwnerKeyInfo = IDL.Record({
  'id' : KeyId,
  'lostMode' : IDL.Bool,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'keyType' : KeyType,
});

export const idlService = IDL.Service({
  'addKey' : IDL.Func([IDL.Text, KeyType], [IDL.Text], []),
  'getKeyInfo' : IDL.Func([IDL.Text], [IDL.Opt(PublicKeyInfo)], ['query']),
  'getMessages' : IDL.Func([IDL.Text], [IDL.Vec(FinderMessage)], ['query']),
  'getMyKeys' : IDL.Func([], [IDL.Vec(OwnerKeyInfo)], ['query']),
  'registerOwner' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'sendFinderMessage' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
      [],
      [],
    ),
  'setLostMode' : IDL.Func([IDL.Text, IDL.Bool], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const KeyType = IDL.Variant({
    'Car' : IDL.Null,
    'Bike' : IDL.Null,
    'Home' : IDL.Null,
    'Office' : IDL.Null,
  });
  const KeyId = IDL.Text;
  const PublicKeyInfo = IDL.Record({
    'id' : KeyId,
    'lostMode' : IDL.Bool,
    'name' : IDL.Text,
    'keyType' : KeyType,
  });
  const Timestamp = IDL.Int;
  const FinderMessage = IDL.Record({
    'id' : IDL.Nat,
    'sentAt' : Timestamp,
    'messageText' : IDL.Text,
    'finderPhone' : IDL.Opt(IDL.Text),
    'keyId' : KeyId,
  });
  const OwnerKeyInfo = IDL.Record({
    'id' : KeyId,
    'lostMode' : IDL.Bool,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'keyType' : KeyType,
  });
  
  return IDL.Service({
    'addKey' : IDL.Func([IDL.Text, KeyType], [IDL.Text], []),
    'getKeyInfo' : IDL.Func([IDL.Text], [IDL.Opt(PublicKeyInfo)], ['query']),
    'getMessages' : IDL.Func([IDL.Text], [IDL.Vec(FinderMessage)], ['query']),
    'getMyKeys' : IDL.Func([], [IDL.Vec(OwnerKeyInfo)], ['query']),
    'registerOwner' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'sendFinderMessage' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [],
        [],
      ),
    'setLostMode' : IDL.Func([IDL.Text, IDL.Bool], [], []),
  });
};

export const init = ({ IDL }) => { return []; };