/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface OwnerKeyInfo {
    id: KeyId;
    lostMode: boolean;
    name: string;
    createdAt: Timestamp;
    keyType: KeyType;
}
export type Timestamp = bigint;
export type KeyId = string;
export interface FinderMessage {
    id: bigint;
    sentAt: Timestamp;
    messageText: string;
    finderPhone?: string;
    keyId: KeyId;
}
export interface PublicKeyInfo {
    id: KeyId;
    lostMode: boolean;
    name: string;
    keyType: KeyType;
}
export enum KeyType {
    Car = "Car",
    Bike = "Bike",
    Home = "Home",
    Office = "Office"
}
export interface backendInterface {
    addKey(name: string, keyType: KeyType): Promise<string>;
    getKeyInfo(keyId: string): Promise<PublicKeyInfo | null>;
    getMessages(keyId: string): Promise<Array<FinderMessage>>;
    getMyKeys(): Promise<Array<OwnerKeyInfo>>;
    registerOwner(name: string, mobile: string): Promise<void>;
    sendFinderMessage(keyId: string, messageText: string, finderPhone: string | null): Promise<void>;
    setLostMode(keyId: string, lostMode: boolean): Promise<void>;
}
import type { FinderMessage as _FinderMessage, KeyId as _KeyId, KeyType as _KeyType, OwnerKeyInfo as _OwnerKeyInfo, PublicKeyInfo as _PublicKeyInfo, Timestamp as _Timestamp } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addKey(arg0: string, arg1: KeyType): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.addKey(arg0, to_candid_KeyType_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addKey(arg0, to_candid_KeyType_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async getKeyInfo(arg0: string): Promise<PublicKeyInfo | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getKeyInfo(arg0);
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getKeyInfo(arg0);
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMessages(arg0: string): Promise<Array<FinderMessage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMessages(arg0);
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMessages(arg0);
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyKeys(): Promise<Array<OwnerKeyInfo>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyKeys();
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyKeys();
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async registerOwner(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.registerOwner(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerOwner(arg0, arg1);
            return result;
        }
    }
    async sendFinderMessage(arg0: string, arg1: string, arg2: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.sendFinderMessage(arg0, arg1, to_candid_opt_n15(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendFinderMessage(arg0, arg1, to_candid_opt_n15(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async setLostMode(arg0: string, arg1: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setLostMode(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setLostMode(arg0, arg1);
            return result;
        }
    }
}
function from_candid_FinderMessage_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FinderMessage): FinderMessage {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_KeyType_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _KeyType): KeyType {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_OwnerKeyInfo_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OwnerKeyInfo): OwnerKeyInfo {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_PublicKeyInfo_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PublicKeyInfo): PublicKeyInfo {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PublicKeyInfo]): PublicKeyInfo | null {
    return value.length === 0 ? null : from_candid_PublicKeyInfo_n4(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    sentAt: _Timestamp;
    messageText: string;
    finderPhone: [] | [string];
    keyId: _KeyId;
}): {
    id: bigint;
    sentAt: Timestamp;
    messageText: string;
    finderPhone?: string;
    keyId: KeyId;
} {
    return {
        id: value.id,
        sentAt: value.sentAt,
        messageText: value.messageText,
        finderPhone: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.finderPhone)),
        keyId: value.keyId
    };
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _KeyId;
    lostMode: boolean;
    name: string;
    createdAt: _Timestamp;
    keyType: _KeyType;
}): {
    id: KeyId;
    lostMode: boolean;
    name: string;
    createdAt: Timestamp;
    keyType: KeyType;
} {
    return {
        id: value.id,
        lostMode: value.lostMode,
        name: value.name,
        createdAt: value.createdAt,
        keyType: from_candid_KeyType_n6(_uploadFile, _downloadFile, value.keyType)
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _KeyId;
    lostMode: boolean;
    name: string;
    keyType: _KeyType;
}): {
    id: KeyId;
    lostMode: boolean;
    name: string;
    keyType: KeyType;
} {
    return {
        id: value.id,
        lostMode: value.lostMode,
        name: value.name,
        keyType: from_candid_KeyType_n6(_uploadFile, _downloadFile, value.keyType)
    };
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Car: null;
} | {
    Bike: null;
} | {
    Home: null;
} | {
    Office: null;
}): KeyType {
    return "Car" in value ? KeyType.Car : "Bike" in value ? KeyType.Bike : "Home" in value ? KeyType.Home : "Office" in value ? KeyType.Office : value;
}
function from_candid_vec_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_OwnerKeyInfo>): Array<OwnerKeyInfo> {
    return value.map((x)=>from_candid_OwnerKeyInfo_n13(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_FinderMessage>): Array<FinderMessage> {
    return value.map((x)=>from_candid_FinderMessage_n9(_uploadFile, _downloadFile, x));
}
function to_candid_KeyType_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: KeyType): _KeyType {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: KeyType): {
    Car: null;
} | {
    Bike: null;
} | {
    Home: null;
} | {
    Office: null;
} {
    return value == KeyType.Car ? {
        Car: null
    } : value == KeyType.Bike ? {
        Bike: null
    } : value == KeyType.Home ? {
        Home: null
    } : value == KeyType.Office ? {
        Office: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
